// Code generated by ghtmx - DO NOT EDIT.

package testjsusage

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/go-monolith/ghtmx"
import ghtmxruntime "github.com/go-monolith/ghtmx/runtime"

import "time"

var onceHandle = ghtmx.NewOnceHandle()

func TestComponent() ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Release := ghtmxruntime.AcquireBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmx_7f3b9d1a_Release(&ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var1 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var1 == nil {
			ghtmx_7f3b9d1a_Var1 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmx.RenderScriptItems(ctx, ghtmx_7f3b9d1a_Buffer, ghtmx.JSFuncCall("alert", "Hello, World!"))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 1, "<button onClick=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var2 ghtmx.ComponentScript = ghtmx.JSFuncCall("alert", "Hello, World!")
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var2.Call)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 2, "\">Click me</button>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Var3 := ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
			ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
			ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Release := ghtmxruntime.AcquireBuffer(ghtmx_7f3b9d1a_W)
			defer ghtmx_7f3b9d1a_Release(&ghtmx_7f3b9d1a_Err)
			ctx = ghtmx.InitializeContext(ctx)
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 3, "<script>\n\t\t\tfunction customAlert(msg, date) {\n\t\t\t\talert(msg + \" \" + date);\n\t\t\t}\n\t\t</script>")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			return nil
		})
		ghtmx_7f3b9d1a_Err = onceHandle.Once().Render(ghtmx.WithChildren(ctx, ghtmx_7f3b9d1a_Var3), ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmx.RenderScriptItems(ctx, ghtmx_7f3b9d1a_Buffer, ghtmx.JSFuncCall("customAlert", "Hello, custom alert 1: ", time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 4, "<button onClick=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var4 ghtmx.ComponentScript = ghtmx.JSFuncCall("customAlert", "Hello, custom alert 1: ", time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC))
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var4.Call)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 5, "\">Click me</button> ")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmx.RenderScriptItems(ctx, ghtmx_7f3b9d1a_Buffer, ghtmx.JSFuncCall("customAlert", "Hello, custom alert 2: ", time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 6, "<button onClick=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var5 ghtmx.ComponentScript = ghtmx.JSFuncCall("customAlert", "Hello, custom alert 2: ", time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC))
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var5.Call)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 7, "\">Click me</button>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmx.JSFuncCall("customAlert", "Runs on page load", time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)).Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 8, "<script>\n\t\tfunction onClickEventHandler(event, data) {\n\t\t\talert(event.type);\n\t\t\talert(data);\n\t\t\tevent.preventDefault();\n\t\t}\n\t</script>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmx.RenderScriptItems(ctx, ghtmx_7f3b9d1a_Buffer, ghtmx.JSFuncCall("onClickEventHandler", ghtmx.JSExpression("event"), "1234"))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 9, "<button onclick=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var6 ghtmx.ComponentScript = ghtmx.JSFuncCall("onClickEventHandler", ghtmx.JSExpression("event"), "1234")
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var6.Call)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 10, "\">Pass event handler</button><div x-data=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var7 string
		ghtmx_7f3b9d1a_Var7, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue(ghtmx.JSFuncCall("alert", "Hello, World!"))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `internal/generator/test-js-usage/template.ghtmx`, Line: 27, Col: 57}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var7)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 11, "\">test</div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

var _ = ghtmxruntime.GeneratedTemplate
