// Code generated by ghtmx - DO NOT EDIT.

package testcall

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/go-monolith/ghtmx"
import ghtmxruntime "github.com/go-monolith/ghtmx/runtime"

func showAll() ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		if !ghtmx_7f3b9d1a_IsBuffer {
			defer func() {
				ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
				if ghtmx_7f3b9d1a_Err == nil {
					ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
				}
			}()
		}
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var1 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var1 == nil {
			ghtmx_7f3b9d1a_Var1 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = a().Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = b(c("C")).Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = d().Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = showOne(e()).Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Var2 := ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
			ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
			ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
			if !ghtmx_7f3b9d1a_IsBuffer {
				defer func() {
					ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
					if ghtmx_7f3b9d1a_Err == nil {
						ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
					}
				}()
			}
			ctx = ghtmx.InitializeContext(ctx)
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 1, "<div>Child content</div>")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			return nil
		})
		ghtmx_7f3b9d1a_Err = wrapChildren().Render(ghtmx.WithChildren(ctx, ghtmx_7f3b9d1a_Var2), ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func a() ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		if !ghtmx_7f3b9d1a_IsBuffer {
			defer func() {
				ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
				if ghtmx_7f3b9d1a_Err == nil {
					ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
				}
			}()
		}
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var3 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var3 == nil {
			ghtmx_7f3b9d1a_Var3 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 2, "<div>A</div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func b(child ghtmx.Component) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		if !ghtmx_7f3b9d1a_IsBuffer {
			defer func() {
				ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
				if ghtmx_7f3b9d1a_Err == nil {
					ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
				}
			}()
		}
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var4 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var4 == nil {
			ghtmx_7f3b9d1a_Var4 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 3, "<div>B</div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = child.Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func c(text string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		if !ghtmx_7f3b9d1a_IsBuffer {
			defer func() {
				ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
				if ghtmx_7f3b9d1a_Err == nil {
					ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
				}
			}()
		}
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var5 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var5 == nil {
			ghtmx_7f3b9d1a_Var5 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 4, "<div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var6 string
		ghtmx_7f3b9d1a_Var6, ghtmx_7f3b9d1a_Err = ghtmx.JoinStringErrs(text)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `internal/generator/test-call/template.ghtmx`, Line: 23, Col: 12}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var6))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 5, "</div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func d() ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		if !ghtmx_7f3b9d1a_IsBuffer {
			defer func() {
				ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
				if ghtmx_7f3b9d1a_Err == nil {
					ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
				}
			}()
		}
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var7 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var7 == nil {
			ghtmx_7f3b9d1a_Var7 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 6, "<div>Legacy call style</div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func e() ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		if !ghtmx_7f3b9d1a_IsBuffer {
			defer func() {
				ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
				if ghtmx_7f3b9d1a_Err == nil {
					ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
				}
			}()
		}
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var8 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var8 == nil {
			ghtmx_7f3b9d1a_Var8 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 7, "e")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func showOne(component ghtmx.Component) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		if !ghtmx_7f3b9d1a_IsBuffer {
			defer func() {
				ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
				if ghtmx_7f3b9d1a_Err == nil {
					ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
				}
			}()
		}
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var9 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var9 == nil {
			ghtmx_7f3b9d1a_Var9 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 8, "<div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = component.Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 9, "</div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func wrapChildren() ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		if !ghtmx_7f3b9d1a_IsBuffer {
			defer func() {
				ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
				if ghtmx_7f3b9d1a_Err == nil {
					ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
				}
			}()
		}
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var10 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var10 == nil {
			ghtmx_7f3b9d1a_Var10 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 10, "<div id=\"wrapper\">")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Var10.Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 11, "</div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

var _ = ghtmxruntime.GeneratedTemplate
