// Code generated by ghtmx - DO NOT EDIT.

// Package ghtmxgen is the central generated package: route path
// constants and typed route constructors, regenerated by ghtmx generate
// from the application's own route registrations.
package ghtmxgen

import (
	"github.com/go-monolith/ghtmx"
)

// AssignPath is the path of POST /inherit/assign -> github.com/go-monolith/ghtmx/examples/htmx4-inheritance.Assign (examples/htmx4-inheritance/inheritance.go).
const AssignPath = "/inherit/assign"

// InheritHomePath is the path of GET /inherit -> github.com/go-monolith/ghtmx/examples/htmx4-inheritance.inheritHome (examples/htmx4-inheritance/inheritance.go).
const InheritHomePath = "/inherit"

// HTMXScript renders the script tag for the configured htmx version
// (4.0.0) with its subresource-integrity hash (FR-091): the served asset
// must be that exact published build or the browser refuses it (FR-052).
func HTMXScript(opts ...ghtmx.ScriptOption) ghtmx.Component {
	return ghtmx.HTMXScriptTag("4.0.0", opts...)
}
