// Code generated by ghtmx - DO NOT EDIT.

package conformance

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/go-monolith/ghtmx"
import ghtmxruntime "github.com/go-monolith/ghtmx/runtime"

import "github.com/go-monolith/ghtmx/ghtmxgen"

// The NFR-007 rendering conformance corpus: one template per supported
// output context, driven by conformance_test.go with hostile inputs and
// exact expected HTML.
func TextContext(s string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var1 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var1 == nil {
			ghtmx_7f3b9d1a_Var1 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 1, "<p>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var2 string
		ghtmx_7f3b9d1a_Var2, ghtmx_7f3b9d1a_Err = ghtmx.JoinStringErrs(s)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `conformance/conformance.ghtmx`, Line: 10, Col: 7}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var2))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 2, "</p>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func AttributeContext(s string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var3 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var3 == nil {
			ghtmx_7f3b9d1a_Var3 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 3, "<div title=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var4 string
		ghtmx_7f3b9d1a_Var4, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue(s)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `conformance/conformance.ghtmx`, Line: 14, Col: 15}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var4)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 4, "\">x</div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func URLContext(s string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var5 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var5 == nil {
			ghtmx_7f3b9d1a_Var5 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 5, "<a href=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var6 ghtmx.SafeURL
		ghtmx_7f3b9d1a_Var6, ghtmx_7f3b9d1a_Err = ghtmx.JoinURLErrs(ghtmx.URL(s))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `conformance/conformance.ghtmx`, Line: 18, Col: 23}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var6))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 6, "\">link</a>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

// GetItem is generated from the route examples/hx-bindings registers;
// that example carries a matching coupling note. Renaming the handler
// there breaks this mandatory FR-023 case.
func RouteBindingContext(id string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var7 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var7 == nil {
			ghtmx_7f3b9d1a_Var7 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 7, "<button hx-get=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var8 ghtmx.SafeURL = ghtmxgen.GetItem(id)
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(string(ghtmx_7f3b9d1a_Var8)))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 8, "\" hx-target=\"#detail\">load</button>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func JSContext(s string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var9 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var9 == nil {
			ghtmx_7f3b9d1a_Var9 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmx.RenderScriptItems(ctx, ghtmx_7f3b9d1a_Buffer, ghtmx.JSFuncCall("alert", s))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 9, "<button onClick=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var10 ghtmx.ComponentScript = ghtmx.JSFuncCall("alert", s)
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var10.Call)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 10, "\">go</button>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func JSONScriptContext(data any) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var11 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var11 == nil {
			ghtmx_7f3b9d1a_Var11 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmx.JSONScript("conformance-data", data).Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func ScriptElementContext(s string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var12 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var12 == nil {
			ghtmx_7f3b9d1a_Var12 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 11, "<script>\n\t\tvar a = ")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Var13, ghtmx_7f3b9d1a_Err := ghtmxruntime.ScriptContentOutsideStringLiteral(s)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `conformance/conformance.ghtmx`, Line: 38, Col: 14}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var13)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 12, ";\n\t\tvar b = \"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Var14, ghtmx_7f3b9d1a_Err := ghtmxruntime.ScriptContentInsideStringLiteral(s)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `conformance/conformance.ghtmx`, Line: 39, Col: 15}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var14)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 13, "\";\n\t</script>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func StyleAttributeContext(v string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var15 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var15 == nil {
			ghtmx_7f3b9d1a_Var15 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 14, "<button style=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var16 string
		ghtmx_7f3b9d1a_Var16, ghtmx_7f3b9d1a_Err = ghtmxruntime.SanitizeStyleAttributeValues(v)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `conformance/conformance.ghtmx`, Line: 44, Col: 18}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var16))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 15, "\">x</button>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func SpreadAttributesContext(attrs ghtmx.Attributes) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var17 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var17 == nil {
			ghtmx_7f3b9d1a_Var17 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 16, "<div")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmx.RenderAttributes(ctx, ghtmx_7f3b9d1a_Buffer, attrs)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 17, ">x</div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func conformanceColor(value string) ghtmx.CSSClass {
	ghtmx_7f3b9d1a_CSSBuilder := ghtmxruntime.GetBuilder()
	ghtmx_7f3b9d1a_CSSBuilder.WriteString(string(ghtmx.SanitizeCSS(`color`, value)))
	ghtmx_7f3b9d1a_CSSID := ghtmx.CSSID(`conformanceColor`, ghtmx_7f3b9d1a_CSSBuilder.String())
	return ghtmx.ComponentCSSClass{
		ID:    ghtmx_7f3b9d1a_CSSID,
		Class: ghtmx.SafeCSS(`.` + ghtmx_7f3b9d1a_CSSID + `{` + ghtmx_7f3b9d1a_CSSBuilder.String() + `}`),
	}
}

func CSSContext(value string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var18 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var18 == nil {
			ghtmx_7f3b9d1a_Var18 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		var ghtmx_7f3b9d1a_Var19 = []any{conformanceColor(value)}
		ghtmx_7f3b9d1a_Err = ghtmx.RenderCSSItems(ctx, ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Var19...)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 18, "<div class=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var20 string
		ghtmx_7f3b9d1a_Var20, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue(ghtmx.CSSClasses(ghtmx_7f3b9d1a_Var19).String())
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `conformance/conformance.ghtmx`, Line: 1, Col: 0}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var20)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 19, "\">styled</div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func ItemsPage(rows []string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var21 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var21 == nil {
			ghtmx_7f3b9d1a_Var21 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 20, "<ul id=\"items\">")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		for _, row := range rows {
			ghtmx_7f3b9d1a_Err = ghtmxFragmentBody_ConformanceRow(ghtmxruntime.GeneratedComponentInput{Context: ctx, Writer: ghtmx_7f3b9d1a_Buffer}, row)
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 21, "</ul>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

// ghtmxFragmentBody_ConformanceRow is the shared body of fragment ConformanceRow: both entry
// points and every declaration site execute it, so the render modes cannot
// diverge.
func ghtmxFragmentBody_ConformanceRow(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput, row string) (ghtmx_7f3b9d1a_Err error) {
	ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
	if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
		return ghtmx_7f3b9d1a_CtxErr
	}
	ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
	defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
	ctx = ghtmx.InitializeContext(ctx)
	ctx = ghtmx.ClearChildren(ctx)
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 22, "<li>")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var22 string
	ghtmx_7f3b9d1a_Var22, ghtmx_7f3b9d1a_Err = ghtmx.JoinStringErrs(row)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `conformance/conformance.ghtmx`, Line: 63, Col: 13}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var22))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 23, "</li>")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	return nil
}

// ConformanceRow renders the fragment inline as a component.
func ConformanceRow(row string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) error {
		return ghtmxFragmentBody_ConformanceRow(ghtmx_7f3b9d1a_Input, row)
	})
}

// ConformanceRowFragment renders only the fragment, for an htmx swap (FR-031).
func ConformanceRowFragment(row string) ghtmx.Fragment {
	return ghtmxruntime.GeneratedFragment(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) error {
		return ghtmxFragmentBody_ConformanceRow(ghtmx_7f3b9d1a_Input, row)
	})
}

func StyleMapContext(m map[string]string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var23 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var23 == nil {
			ghtmx_7f3b9d1a_Var23 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 24, "<button style=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var24 string
		ghtmx_7f3b9d1a_Var24, ghtmx_7f3b9d1a_Err = ghtmxruntime.SanitizeStyleAttributeValues(m)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `conformance/conformance.ghtmx`, Line: 70, Col: 18}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var24))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 25, "\">x</button>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

var _ = ghtmxruntime.GeneratedTemplate
