// Code generated by ghtmx - DO NOT EDIT.

package crud

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/go-monolith/ghtmx"
import ghtmxruntime "github.com/go-monolith/ghtmx/runtime"

import "github.com/go-monolith/ghtmx/ghtmxgen"

// The MVP acceptance application (task 67): full CRUD over todos with
// htmx partial updates through compile-time fragments, route-aware
// bindings, and the server-driven event contract. There is no
// hand-written htmx glue anywhere: every URL comes from a binding,
// every HX-Trigger from a generated emitter, and the htmx script tag
// from the pinned helper.

// The event contract: these declarations are the only source of the
// Emit* symbols the handlers use. The stats panel listens for them.
func todoPage(todos []Todo, total int, done int) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		if !ghtmx_7f3b9d1a_IsBuffer {
			defer func() {
				ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
				if ghtmx_7f3b9d1a_Err == nil {
					ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
				}
			}()
		}
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var1 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var1 == nil {
			ghtmx_7f3b9d1a_Var1 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 1, "<!doctype html><html><head><title>ghtmx todos</title>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxgen.HTMXScript().Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 2, "</head><body><h1>Todos</h1>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = statsPanel(total, done).Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 3, "<form hx-post=\"/todos\" hx-target=\"#todo-list\" hx-swap=\"outerHTML\"><input type=\"text\" name=\"title\" placeholder=\"What needs doing?\" required> <button type=\"submit\">Add</button></form><button hx-get=\"/todos\" hx-target=\"#todo-list\" hx-swap=\"outerHTML\">refresh</button>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = todoList(todos).Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 4, "</body></html>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

// statsPanel refreshes itself whenever any contract event fires
// anywhere on the page.
// ghtmxFragmentBody_statsPanel is the shared body of fragment statsPanel: both entry
// points and every declaration site execute it, so the render modes cannot
// diverge.
func ghtmxFragmentBody_statsPanel(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput, total int, done int) (ghtmx_7f3b9d1a_Err error) {
	ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
	if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
		return ghtmx_7f3b9d1a_CtxErr
	}
	ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
	if !ghtmx_7f3b9d1a_IsBuffer {
		defer func() {
			ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
			if ghtmx_7f3b9d1a_Err == nil {
				ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
			}
		}()
	}
	ctx = ghtmx.InitializeContext(ctx)
	ctx = ghtmx.ClearChildren(ctx)
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 5, "<div id=\"todo-stats\" hx-get=\"/todos/stats\" hx-trigger=\"todo-created from:body, todo-toggled from:body, todo-deleted from:body\" hx-swap=\"outerHTML\"><span>")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var2 string
	ghtmx_7f3b9d1a_Var2, ghtmx_7f3b9d1a_Err = ghtmx.JoinStringErrs(itoa(done))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/crud/crud.ghtmx`, Line: 57, Col: 20}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var2))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 6, " of ")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var3 string
	ghtmx_7f3b9d1a_Var3, ghtmx_7f3b9d1a_Err = ghtmx.JoinStringErrs(itoa(total))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/crud/crud.ghtmx`, Line: 57, Col: 39}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var3))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 7, " done</span></div>")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	return nil
}

// statsPanel renders the fragment inline as a component.
func statsPanel(total int, done int) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) error {
		return ghtmxFragmentBody_statsPanel(ghtmx_7f3b9d1a_Input, total, done)
	})
}

// statsPanelFragment renders only the fragment, for an htmx swap (FR-031).
func statsPanelFragment(total int, done int) ghtmx.Fragment {
	return ghtmxruntime.GeneratedFragment(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) error {
		return ghtmxFragmentBody_statsPanel(ghtmx_7f3b9d1a_Input, total, done)
	})
}

// The list is itself a fragment: the page embeds it inline, and the
// standalone entry point serves htmx refreshes byte-identically.
// ghtmxFragmentBody_todoList is the shared body of fragment todoList: both entry
// points and every declaration site execute it, so the render modes cannot
// diverge.
func ghtmxFragmentBody_todoList(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput, todos []Todo) (ghtmx_7f3b9d1a_Err error) {
	ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
	if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
		return ghtmx_7f3b9d1a_CtxErr
	}
	ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
	if !ghtmx_7f3b9d1a_IsBuffer {
		defer func() {
			ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
			if ghtmx_7f3b9d1a_Err == nil {
				ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
			}
		}()
	}
	ctx = ghtmx.InitializeContext(ctx)
	ctx = ghtmx.ClearChildren(ctx)
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 8, "<table id=\"todo-list\">")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	for _, t := range todos {
		ghtmx_7f3b9d1a_Err = ghtmxFragmentBody_todoRow(ghtmxruntime.GeneratedComponentInput{Context: ctx, Writer: ghtmx_7f3b9d1a_Buffer}, t)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 9, "</table>")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	return nil
}

// todoList renders the fragment inline as a component.
func todoList(todos []Todo) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) error {
		return ghtmxFragmentBody_todoList(ghtmx_7f3b9d1a_Input, todos)
	})
}

// todoListFragment renders only the fragment, for an htmx swap (FR-031).
func todoListFragment(todos []Todo) ghtmx.Fragment {
	return ghtmxruntime.GeneratedFragment(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) error {
		return ghtmxFragmentBody_todoList(ghtmx_7f3b9d1a_Input, todos)
	})
}

// ghtmxFragmentBody_todoRow is the shared body of fragment todoRow: both entry
// points and every declaration site execute it, so the render modes cannot
// diverge.
func ghtmxFragmentBody_todoRow(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput, t Todo) (ghtmx_7f3b9d1a_Err error) {
	ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
	if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
		return ghtmx_7f3b9d1a_CtxErr
	}
	ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
	if !ghtmx_7f3b9d1a_IsBuffer {
		defer func() {
			ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
			if ghtmx_7f3b9d1a_Err == nil {
				ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
			}
		}()
	}
	ctx = ghtmx.InitializeContext(ctx)
	ctx = ghtmx.ClearChildren(ctx)
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 10, "<tr id=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var4 string
	ghtmx_7f3b9d1a_Var4, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue("todo-" + t.ID)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/crud/crud.ghtmx`, Line: 67, Col: 27}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var4)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 11, "\">")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var5 = []any{doneClass(t.Done)}
	ghtmx_7f3b9d1a_Err = ghtmx.RenderCSSItems(ctx, ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Var5...)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 12, "<td class=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var6 string
	ghtmx_7f3b9d1a_Var6, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue(ghtmx.CSSClasses(ghtmx_7f3b9d1a_Var5).String())
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/crud/crud.ghtmx`, Line: 1, Col: 0}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var6)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 13, "\">")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var7 string
	ghtmx_7f3b9d1a_Var7, ghtmx_7f3b9d1a_Err = ghtmx.JoinStringErrs(t.Title)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/crud/crud.ghtmx`, Line: 68, Col: 46}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var7))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 14, "</td><td><button hx-get=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var8 ghtmx.SafeURL = ghtmxgen.EditTodo(t.ID)
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(string(ghtmx_7f3b9d1a_Var8)))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 15, "\" hx-target=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var9 string
	ghtmx_7f3b9d1a_Var9, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue("#todo-" + t.ID)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/crud/crud.ghtmx`, Line: 72, Col: 34}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var9)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 16, "\" hx-swap=\"outerHTML\">edit</button></td><td><button hx-put=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var10 ghtmx.SafeURL = ghtmxgen.ToggleTodo(t.ID)
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(string(ghtmx_7f3b9d1a_Var10)))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 17, "\" hx-target=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var11 string
	ghtmx_7f3b9d1a_Var11, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue("#todo-" + t.ID)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/crud/crud.ghtmx`, Line: 79, Col: 34}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var11)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 18, "\" hx-swap=\"outerHTML\">toggle</button></td><td><button hx-delete=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var12 ghtmx.SafeURL = ghtmxgen.DeleteTodo(t.ID)
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(string(ghtmx_7f3b9d1a_Var12)))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 19, "\" hx-target=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var13 string
	ghtmx_7f3b9d1a_Var13, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue("#todo-" + t.ID)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/crud/crud.ghtmx`, Line: 86, Col: 34}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var13)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 20, "\" hx-swap=\"outerHTML\">delete</button></td></tr>")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	return nil
}

// todoRow renders the fragment inline as a component.
func todoRow(t Todo) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) error {
		return ghtmxFragmentBody_todoRow(ghtmx_7f3b9d1a_Input, t)
	})
}

// todoRowFragment renders only the fragment, for an htmx swap (FR-031).
func todoRowFragment(t Todo) ghtmx.Fragment {
	return ghtmxruntime.GeneratedFragment(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) error {
		return ghtmxFragmentBody_todoRow(ghtmx_7f3b9d1a_Input, t)
	})
}

// The inline edit flow: the edit button swaps a row for this form, and
// submitting swaps back the refreshed row. The fragment is rendered
// only from the EditTodo handler (FR-034's handler-explicit path), so
// generation reports GHTMX-W0101 for it — the reachability check sees
// template references, not Go handler bodies. The warning is the
// documented cost of a handler-only fragment.
// ghtmxFragmentBody_todoEditRow is the shared body of fragment todoEditRow: both entry
// points and every declaration site execute it, so the render modes cannot
// diverge.
func ghtmxFragmentBody_todoEditRow(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput, t Todo) (ghtmx_7f3b9d1a_Err error) {
	ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
	if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
		return ghtmx_7f3b9d1a_CtxErr
	}
	ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
	if !ghtmx_7f3b9d1a_IsBuffer {
		defer func() {
			ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
			if ghtmx_7f3b9d1a_Err == nil {
				ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
			}
		}()
	}
	ctx = ghtmx.InitializeContext(ctx)
	ctx = ghtmx.ClearChildren(ctx)
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 21, "<tr id=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var14 string
	ghtmx_7f3b9d1a_Var14, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue("todo-" + t.ID)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/crud/crud.ghtmx`, Line: 103, Col: 24}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var14)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 22, "\"><td colspan=\"4\"><form hx-put=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var15 ghtmx.SafeURL = ghtmxgen.RenameTodo(t.ID)
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(string(ghtmx_7f3b9d1a_Var15)))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 23, "\" hx-target=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var16 string
	ghtmx_7f3b9d1a_Var16, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue("#todo-" + t.ID)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/crud/crud.ghtmx`, Line: 107, Col: 31}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var16)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 24, "\" hx-swap=\"outerHTML\"><input type=\"text\" name=\"title\" value=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var17 string
	ghtmx_7f3b9d1a_Var17, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue(t.Title)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/crud/crud.ghtmx`, Line: 110, Col: 51}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var17)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 25, "\" required> <button type=\"submit\">Save</button></form></td></tr>")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	return nil
}

// todoEditRow renders the fragment inline as a component.
func todoEditRow(t Todo) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) error {
		return ghtmxFragmentBody_todoEditRow(ghtmx_7f3b9d1a_Input, t)
	})
}

// todoEditRowFragment renders only the fragment, for an htmx swap (FR-031).
func todoEditRowFragment(t Todo) ghtmx.Fragment {
	return ghtmxruntime.GeneratedFragment(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) error {
		return ghtmxFragmentBody_todoEditRow(ghtmx_7f3b9d1a_Input, t)
	})
}

// Handlers bound from hx-* attributes: the references keep imports
// used and the symbols compile-checked.
var (
	_ = CreateTodo
	_ = ListTodos
	_ = TodoStats
)

var _ = ghtmxruntime.GeneratedTemplate
