// Code generated by ghtmx - DO NOT EDIT.

// Package ghtmxgen is the central generated package: route path
// constants and typed route constructors, regenerated by ghtmx generate
// from the application's own route registrations.
package ghtmxgen

import (
	"github.com/go-monolith/ghtmx"
)

// SearchPath is the path of QUERY /search -> github.com/go-monolith/ghtmx/examples/htmx4-query.Search (examples/htmx4-query/query.go).
const SearchPath = "/search"

// SearchHomePath is the path of GET /search -> github.com/go-monolith/ghtmx/examples/htmx4-query.searchHome (examples/htmx4-query/query.go).
const SearchHomePath = "/search"

// HTMXScript renders the script tag for the configured htmx version
// (4.0.0) with its subresource-integrity hash (FR-091): the served asset
// must be that exact published build or the browser refuses it (FR-052).
func HTMXScript(opts ...ghtmx.ScriptOption) ghtmx.Component {
	return ghtmx.HTMXScriptTag("4.0.0", opts...)
}
