// Code generated by ghtmx - DO NOT EDIT.

package onlyscripts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/go-monolith/ghtmx"
import ghtmxruntime "github.com/go-monolith/ghtmx/runtime"

func withParameters(a string, b string, c int) ghtmx.ComponentScript {
	return ghtmx.ComponentScript{
		Name: `__ghtmx_withParameters_1056`,
		Function: `function __ghtmx_withParameters_1056(a, b, c){console.log(a, b, c);
}`,
		Call:       ghtmx.SafeScript(`__ghtmx_withParameters_1056`, a, b, c),
		CallInline: ghtmx.SafeScriptInline(`__ghtmx_withParameters_1056`, a, b, c),
	}
}

var _ = ghtmxruntime.GeneratedTemplate
