// Code generated by ghtmx - DO NOT EDIT.

// Package ghtmxgen is the central generated package: route path
// constants and typed route constructors, regenerated by ghtmx generate
// from the application's own route registrations.
package ghtmxgen

import (
	"github.com/go-monolith/ghtmx"
	ghtmxruntime "github.com/go-monolith/ghtmx/runtime"
	"net/http"
)

// BenchCreatePath is the path of POST /bench/items -> github.com/go-monolith/ghtmx/benchmarks/corpus.BenchCreate (benchmarks/corpus/data.go:42:2).
const BenchCreatePath = "/bench/items"

// BenchItem builds the URL for GET /bench/items/{id} -> github.com/go-monolith/ghtmx/benchmarks/corpus.BenchItem (benchmarks/corpus/data.go:41:2).
func BenchItem(id string) ghtmx.SafeURL {
	return ghtmx.SafeURL("/bench/items/" + ghtmx.EscapePathSegment(id))
}

// CreateTodoPath is the path of POST /todos -> github.com/go-monolith/ghtmx/examples/crud.CreateTodo (examples/crud/main.go:263:2).
const CreateTodoPath = "/todos"

// DeleteTodo builds the URL for DELETE /todos/{id} -> github.com/go-monolith/ghtmx/examples/crud.DeleteTodo (examples/crud/main.go:267:2).
func DeleteTodo(id string) ghtmx.SafeURL {
	return ghtmx.SafeURL("/todos/" + ghtmx.EscapePathSegment(id))
}

// EditTodo builds the URL for GET /todos/{id}/edit -> github.com/go-monolith/ghtmx/examples/crud.EditTodo (examples/crud/main.go:264:2).
func EditTodo(id string) ghtmx.SafeURL {
	return ghtmx.SafeURL("/todos/" + ghtmx.EscapePathSegment(id) + "/edit")
}

// EventsHomePath is the path of GET /events -> github.com/go-monolith/ghtmx/examples/events.eventsHome (examples/events/main.go:69:2).
const EventsHomePath = "/events"

// FragmentsHomePath is the path of GET /fragments -> github.com/go-monolith/ghtmx/examples/fragments.fragmentsHome (examples/fragments/main.go:55:2).
const FragmentsHomePath = "/fragments"

// GetItem builds the URL for GET /items/{id} -> github.com/go-monolith/ghtmx/examples/hx-bindings/handlers.GetItem (examples/hx-bindings/main.go:22:2).
func GetItem(id string) ghtmx.SafeURL {
	return ghtmx.SafeURL("/items/" + ghtmx.EscapePathSegment(id))
}

// HomePath is the path of GET /hello -> github.com/go-monolith/ghtmx/examples/hello-world.home (examples/hello-world/main.go:29:2).
const HomePath = "/hello"

// IndexPath is the path of GET / -> github.com/go-monolith/ghtmx/examples/crud.Index (examples/crud/main.go:261:2).
const IndexPath = "/"

// ListItemsPath is the path of GET /items -> github.com/go-monolith/ghtmx/examples/hx-bindings/handlers.ListItems (examples/hx-bindings/main.go:18:2).
const ListItemsPath = "/items"

// ListTodosPath is the path of GET /todos -> github.com/go-monolith/ghtmx/examples/crud.ListTodos (examples/crud/main.go:262:2).
const ListTodosPath = "/todos"

// RenameTodo builds the URL for PUT /todos/{id}/title -> github.com/go-monolith/ghtmx/examples/crud.RenameTodo (examples/crud/main.go:265:2).
func RenameTodo(id string) ghtmx.SafeURL {
	return ghtmx.SafeURL("/todos/" + ghtmx.EscapePathSegment(id) + "/title")
}

// RowDetail builds the URL for GET /fragments/rows/{id} -> github.com/go-monolith/ghtmx/examples/fragments.rowDetail (examples/fragments/main.go:56:2).
func RowDetail(id string) ghtmx.SafeURL {
	return ghtmx.SafeURL("/fragments/rows/" + ghtmx.EscapePathSegment(id))
}

// SaveItem builds the URL for POST /events/items/{id} -> github.com/go-monolith/ghtmx/examples/events.saveItem (examples/events/main.go:70:2).
func SaveItem(id string) ghtmx.SafeURL {
	return ghtmx.SafeURL("/events/items/" + ghtmx.EscapePathSegment(id))
}

// TodoStatsPath is the path of GET /todos/stats -> github.com/go-monolith/ghtmx/examples/crud.TodoStats (examples/crud/main.go:268:2).
const TodoStatsPath = "/todos/stats"

// ToggleTodo builds the URL for PUT /todos/{id} -> github.com/go-monolith/ghtmx/examples/crud.ToggleTodo (examples/crud/main.go:266:2).
func ToggleTodo(id string) ghtmx.SafeURL {
	return ghtmx.SafeURL("/todos/" + ghtmx.EscapePathSegment(id))
}

// EmitCartCleared appends the payload-less event "cart-cleared" to the response's single
// HX-Trigger header; multiple emissions in one response merge (FR-037).
// Call it before writing the response status or body, from one
// goroutine. Declared at examples/events/page.ghtmx:12:1.
func EmitCartCleared(w http.ResponseWriter) error {
	return ghtmxruntime.AppendTrigger(w, "cart-cleared", nil)
}

// EmitCartClearedAfterSettle appends the payload-less event "cart-cleared" to the response's single
// HX-Trigger-After-Settle header; multiple emissions in one response merge (FR-037).
// Call it before writing the response status or body, from one
// goroutine. Declared at examples/events/page.ghtmx:12:1.
func EmitCartClearedAfterSettle(w http.ResponseWriter) error {
	return ghtmxruntime.AppendTriggerAfterSettle(w, "cart-cleared", nil)
}

// EmitCartClearedAfterSwap appends the payload-less event "cart-cleared" to the response's single
// HX-Trigger-After-Swap header; multiple emissions in one response merge (FR-037).
// Call it before writing the response status or body, from one
// goroutine. Declared at examples/events/page.ghtmx:12:1.
func EmitCartClearedAfterSwap(w http.ResponseWriter) error {
	return ghtmxruntime.AppendTriggerAfterSwap(w, "cart-cleared", nil)
}

// ItemSavedPayload is the payload of event "item-saved" (declared at examples/events/page.ghtmx:10:1).
type ItemSavedPayload struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// EmitItemSaved appends event "item-saved" to the response's single HX-Trigger
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at examples/events/page.ghtmx:10:1.
func EmitItemSaved(w http.ResponseWriter, p ItemSavedPayload) error {
	return ghtmxruntime.AppendTrigger(w, "item-saved", p)
}

// EmitItemSavedAfterSettle appends event "item-saved" to the response's single HX-Trigger-After-Settle
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at examples/events/page.ghtmx:10:1.
func EmitItemSavedAfterSettle(w http.ResponseWriter, p ItemSavedPayload) error {
	return ghtmxruntime.AppendTriggerAfterSettle(w, "item-saved", p)
}

// EmitItemSavedAfterSwap appends event "item-saved" to the response's single HX-Trigger-After-Swap
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at examples/events/page.ghtmx:10:1.
func EmitItemSavedAfterSwap(w http.ResponseWriter, p ItemSavedPayload) error {
	return ghtmxruntime.AppendTriggerAfterSwap(w, "item-saved", p)
}

// TodoCreatedPayload is the payload of event "todo-created" (declared at examples/crud/crud.ghtmx:14:1).
type TodoCreatedPayload struct {
	Id string `json:"id"`
}

// EmitTodoCreated appends event "todo-created" to the response's single HX-Trigger
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at examples/crud/crud.ghtmx:14:1.
func EmitTodoCreated(w http.ResponseWriter, p TodoCreatedPayload) error {
	return ghtmxruntime.AppendTrigger(w, "todo-created", p)
}

// EmitTodoCreatedAfterSettle appends event "todo-created" to the response's single HX-Trigger-After-Settle
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at examples/crud/crud.ghtmx:14:1.
func EmitTodoCreatedAfterSettle(w http.ResponseWriter, p TodoCreatedPayload) error {
	return ghtmxruntime.AppendTriggerAfterSettle(w, "todo-created", p)
}

// EmitTodoCreatedAfterSwap appends event "todo-created" to the response's single HX-Trigger-After-Swap
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at examples/crud/crud.ghtmx:14:1.
func EmitTodoCreatedAfterSwap(w http.ResponseWriter, p TodoCreatedPayload) error {
	return ghtmxruntime.AppendTriggerAfterSwap(w, "todo-created", p)
}

// TodoDeletedPayload is the payload of event "todo-deleted" (declared at examples/crud/crud.ghtmx:18:1).
type TodoDeletedPayload struct {
	Id string `json:"id"`
}

// EmitTodoDeleted appends event "todo-deleted" to the response's single HX-Trigger
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at examples/crud/crud.ghtmx:18:1.
func EmitTodoDeleted(w http.ResponseWriter, p TodoDeletedPayload) error {
	return ghtmxruntime.AppendTrigger(w, "todo-deleted", p)
}

// EmitTodoDeletedAfterSettle appends event "todo-deleted" to the response's single HX-Trigger-After-Settle
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at examples/crud/crud.ghtmx:18:1.
func EmitTodoDeletedAfterSettle(w http.ResponseWriter, p TodoDeletedPayload) error {
	return ghtmxruntime.AppendTriggerAfterSettle(w, "todo-deleted", p)
}

// EmitTodoDeletedAfterSwap appends event "todo-deleted" to the response's single HX-Trigger-After-Swap
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at examples/crud/crud.ghtmx:18:1.
func EmitTodoDeletedAfterSwap(w http.ResponseWriter, p TodoDeletedPayload) error {
	return ghtmxruntime.AppendTriggerAfterSwap(w, "todo-deleted", p)
}

// TodoToggledPayload is the payload of event "todo-toggled" (declared at examples/crud/crud.ghtmx:16:1).
type TodoToggledPayload struct {
	Id   string `json:"id"`
	Done bool   `json:"done"`
}

// EmitTodoToggled appends event "todo-toggled" to the response's single HX-Trigger
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at examples/crud/crud.ghtmx:16:1.
func EmitTodoToggled(w http.ResponseWriter, p TodoToggledPayload) error {
	return ghtmxruntime.AppendTrigger(w, "todo-toggled", p)
}

// EmitTodoToggledAfterSettle appends event "todo-toggled" to the response's single HX-Trigger-After-Settle
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at examples/crud/crud.ghtmx:16:1.
func EmitTodoToggledAfterSettle(w http.ResponseWriter, p TodoToggledPayload) error {
	return ghtmxruntime.AppendTriggerAfterSettle(w, "todo-toggled", p)
}

// EmitTodoToggledAfterSwap appends event "todo-toggled" to the response's single HX-Trigger-After-Swap
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at examples/crud/crud.ghtmx:16:1.
func EmitTodoToggledAfterSwap(w http.ResponseWriter, p TodoToggledPayload) error {
	return ghtmxruntime.AppendTriggerAfterSwap(w, "todo-toggled", p)
}

// HTMXScript renders the script tag for the configured htmx version
// (2.0.10) with its subresource-integrity hash (FR-091): the served asset
// must be that exact published build or the browser refuses it (FR-052).
func HTMXScript(opts ...ghtmx.ScriptOption) ghtmx.Component {
	return ghtmx.HTMXScriptTag("2.0.10", opts...)
}
