// Code generated by ghtmx - DO NOT EDIT.

package events

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/go-monolith/ghtmx"
import ghtmxruntime "github.com/go-monolith/ghtmx/runtime"

// ghtmx.CSRFHeader needs no import: generated code always imports the
// ghtmx runtime.
import "github.com/go-monolith/ghtmx/ghtmxgen"

// The server-driven event contract (FR-037): these declarations are the
// only source of the EmitItemSaved / EmitCartCleared symbols and their
// payload types in ghtmxgen.
func eventsPage(items []Item, csrf string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		if !ghtmx_7f3b9d1a_IsBuffer {
			defer func() {
				ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
				if ghtmx_7f3b9d1a_Err == nil {
					ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
				}
			}()
		}
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var1 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var1 == nil {
			ghtmx_7f3b9d1a_Var1 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 1, "<div id=\"board\" hx-on:item-saved=\"this.dataset.last = event.detail.id\"><table id=\"items\"><tbody>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		for _, it := range items {
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 2, "<tr id=\"")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			var ghtmx_7f3b9d1a_Var2 string
			ghtmx_7f3b9d1a_Var2, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue("item-" + it.ID)
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/events/page.ghtmx`, Line: 19, Col: 29}
			}
			_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var2)
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 3, "\"><td>")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			var ghtmx_7f3b9d1a_Var3 string
			ghtmx_7f3b9d1a_Var3, ghtmx_7f3b9d1a_Err = ghtmx.JoinStringErrs(it.Name)
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/events/page.ghtmx`, Line: 20, Col: 19}
			}
			_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var3))
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 4, "</td><td><button hx-post=\"")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			var ghtmx_7f3b9d1a_Var4 ghtmx.SafeURL = ghtmxgen.SaveItem(it.ID)
			_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(string(ghtmx_7f3b9d1a_Var4)))
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 5, "\" hx-headers=\"")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			var ghtmx_7f3b9d1a_Var5 string
			ghtmx_7f3b9d1a_Var5, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue(ghtmx.CSRFHeader(csrf))
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/events/page.ghtmx`, Line: 22, Col: 87}
			}
			_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var5)
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 6, "\" hx-target=\"")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			var ghtmx_7f3b9d1a_Var6 string
			ghtmx_7f3b9d1a_Var6, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue("#item-" + it.ID)
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `examples/events/page.ghtmx`, Line: 22, Col: 118}
			}
			_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var6)
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 7, "\" hx-swap=\"outerHTML\">Save</button></td></tr>")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 8, "</tbody></table><div id=\"cart\" hx-get=\"/events\" hx-trigger=\"cart-cleared from:body\" hx-target=\"#cart\" hx-select=\"#cart\" hx-swap=\"outerHTML\"></div></div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

// Handlers bound from hx-* attributes: the references keep imports
// used and the symbols compile-checked.
var (
	_ = eventsHome
)

var _ = ghtmxruntime.GeneratedTemplate
