// Code generated by ghtmx - DO NOT EDIT.

// Package ghtmxgen is the central generated package: route path
// constants and typed route constructors, regenerated by ghtmx generate
// from the application's own route registrations.
package ghtmxgen

import (
	"github.com/go-monolith/ghtmx"
	ghtmxruntime "github.com/go-monolith/ghtmx/runtime"
	"net/http"
)

// DocPage builds the URL for GET /docs/{slug} -> github.com/go-monolith/ghtmx/docs/official/site.DocPage (site/handlers.go:28:2).
func DocPage(slug string) ghtmx.SafeURL {
	return ghtmx.SafeURL("/docs/" + ghtmx.EscapePathSegment(slug))
}

// ExampleDetail builds the URL for GET /examples/{name} -> github.com/go-monolith/ghtmx/docs/official/site.ExampleDetail (site/handlers.go:30:2).
func ExampleDetail(name string) ghtmx.SafeURL {
	return ghtmx.SafeURL("/examples/" + ghtmx.EscapePathSegment(name))
}

// ExamplesIndexPath is the path of GET /examples -> github.com/go-monolith/ghtmx/docs/official/site.ExamplesIndex (site/handlers.go:29:2).
const ExamplesIndexPath = "/examples"

// GettingStartedPath is the path of GET /getting-started -> github.com/go-monolith/ghtmx/docs/official/site.GettingStarted (site/handlers.go:26:2).
const GettingStartedPath = "/getting-started"

// HomePath is the path of GET / -> github.com/go-monolith/ghtmx/docs/official/site.Home (site/handlers.go:25:2).
const HomePath = "/"

// SyntaxSection builds the URL for GET /docs/syntax/{section} -> github.com/go-monolith/ghtmx/docs/official/site.SyntaxSection (site/handlers.go:27:2).
func SyntaxSection(section string) ghtmx.SafeURL {
	return ghtmx.SafeURL("/docs/syntax/" + ghtmx.EscapePathSegment(section))
}

// DocViewedPayload is the payload of event "doc-viewed" (declared at site/layout.ghtmx:8:1).
type DocViewedPayload struct {
	Slug string `json:"slug"`
}

// EmitDocViewed appends event "doc-viewed" to the response's single HX-Trigger
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at site/layout.ghtmx:8:1.
func EmitDocViewed(w http.ResponseWriter, p DocViewedPayload) error {
	return ghtmxruntime.AppendTrigger(w, "doc-viewed", p)
}

// EmitDocViewedAfterSettle appends event "doc-viewed" to the response's single HX-Trigger-After-Settle
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at site/layout.ghtmx:8:1.
func EmitDocViewedAfterSettle(w http.ResponseWriter, p DocViewedPayload) error {
	return ghtmxruntime.AppendTriggerAfterSettle(w, "doc-viewed", p)
}

// EmitDocViewedAfterSwap appends event "doc-viewed" to the response's single HX-Trigger-After-Swap
// header; multiple emissions in one response merge (FR-037). Call it
// before writing the response status or body, from one goroutine.
// Declared at site/layout.ghtmx:8:1.
func EmitDocViewedAfterSwap(w http.ResponseWriter, p DocViewedPayload) error {
	return ghtmxruntime.AppendTriggerAfterSwap(w, "doc-viewed", p)
}

// HTMXScript renders the script tag for the configured htmx version
// (2.0.10) with its subresource-integrity hash (FR-091): the served asset
// must be that exact published build or the browser refuses it (FR-052).
func HTMXScript(opts ...ghtmx.ScriptOption) ghtmx.Component {
	return ghtmx.HTMXScriptTag("2.0.10", opts...)
}
