// Code generated by ghtmx - DO NOT EDIT.

package testelementattributes

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/go-monolith/ghtmx"
import ghtmxruntime "github.com/go-monolith/ghtmx/runtime"

func important() ghtmx.CSSClass {
	ghtmx_7f3b9d1a_CSSBuilder := ghtmxruntime.GetBuilder()
	ghtmx_7f3b9d1a_CSSBuilder.WriteString(`width:100;`)
	ghtmx_7f3b9d1a_CSSID := ghtmx.CSSID(`important`, ghtmx_7f3b9d1a_CSSBuilder.String())
	return ghtmx.ComponentCSSClass{
		ID:    ghtmx_7f3b9d1a_CSSID,
		Class: ghtmx.SafeCSS(`.` + ghtmx_7f3b9d1a_CSSID + `{` + ghtmx_7f3b9d1a_CSSBuilder.String() + `}`),
	}
}

func unimportant() ghtmx.CSSClass {
	ghtmx_7f3b9d1a_CSSBuilder := ghtmxruntime.GetBuilder()
	ghtmx_7f3b9d1a_CSSBuilder.WriteString(`width:50;`)
	ghtmx_7f3b9d1a_CSSID := ghtmx.CSSID(`unimportant`, ghtmx_7f3b9d1a_CSSBuilder.String())
	return ghtmx.ComponentCSSClass{
		ID:    ghtmx_7f3b9d1a_CSSID,
		Class: ghtmx.SafeCSS(`.` + ghtmx_7f3b9d1a_CSSID + `{` + ghtmx_7f3b9d1a_CSSBuilder.String() + `}`),
	}
}

func render(p person) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		if !ghtmx_7f3b9d1a_IsBuffer {
			defer func() {
				ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
				if ghtmx_7f3b9d1a_Err == nil {
					ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
				}
			}()
		}
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var1 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var1 == nil {
			ghtmx_7f3b9d1a_Var1 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		var ghtmx_7f3b9d1a_Var2 = []any{important()}
		ghtmx_7f3b9d1a_Err = ghtmx.RenderCSSItems(ctx, ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Var2...)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 1, "<div style=\"width: 100\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		if p.important {
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 2, " class=\"")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			var ghtmx_7f3b9d1a_Var3 string
			ghtmx_7f3b9d1a_Var3, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue(ghtmx.CSSClasses(ghtmx_7f3b9d1a_Var2).String())
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `internal/generator/test-element-attributes/template.ghtmx`, Line: 1, Col: 0}
			}
			_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var3)
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 3, "\"")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 4, ">Important</div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var4 = []any{unimportant}
		ghtmx_7f3b9d1a_Err = ghtmx.RenderCSSItems(ctx, ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Var4...)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 5, "<div style=\"width: 100\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		if !p.important {
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 6, " class=\"")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			var ghtmx_7f3b9d1a_Var5 string
			ghtmx_7f3b9d1a_Var5, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue(ghtmx.CSSClasses(ghtmx_7f3b9d1a_Var4).String())
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `internal/generator/test-element-attributes/template.ghtmx`, Line: 1, Col: 0}
			}
			_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var5)
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 7, "\"")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 8, ">Unimportant</div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var6 = []any{important}
		ghtmx_7f3b9d1a_Err = ghtmx.RenderCSSItems(ctx, ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Var6...)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var7 = []any{unimportant}
		ghtmx_7f3b9d1a_Err = ghtmx.RenderCSSItems(ctx, ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Var7...)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 9, "<div style=\"width: 100\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		if p.important {
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 10, " class=\"")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			var ghtmx_7f3b9d1a_Var8 string
			ghtmx_7f3b9d1a_Var8, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue(ghtmx.CSSClasses(ghtmx_7f3b9d1a_Var6).String())
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `internal/generator/test-element-attributes/template.ghtmx`, Line: 1, Col: 0}
			}
			_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var8)
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 11, "\"")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
		} else {
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 12, " class=\"")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			var ghtmx_7f3b9d1a_Var9 string
			ghtmx_7f3b9d1a_Var9, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue(ghtmx.CSSClasses(ghtmx_7f3b9d1a_Var7).String())
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `internal/generator/test-element-attributes/template.ghtmx`, Line: 1, Col: 0}
			}
			_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var9)
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 13, "\"")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 14, ">Else</div><div data-script=\"on click\n                do something\n             end\"></div><h2>htmx Wildcard attribute</h2><form")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var10 string
		ghtmx_7f3b9d1a_Var10, ghtmx_7f3b9d1a_Err = ghtmx.JoinStringErrs("dynamic" + "-attr-key")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `internal/generator/test-element-attributes/template.ghtmx`, Line: 39, Col: 25}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(` ` + ghtmx_7f3b9d1a_Var10))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 15, "=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var11 string
		ghtmx_7f3b9d1a_Var11, ghtmx_7f3b9d1a_Err = ghtmx.ResolveAttributeValue("hello world")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `internal/generator/test-element-attributes/template.ghtmx`, Line: 39, Col: 43}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var11)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 16, "\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var12 string
		ghtmx_7f3b9d1a_Var12, ghtmx_7f3b9d1a_Err = ghtmx.JoinStringErrs("dynamic" + "-const-key")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `internal/generator/test-element-attributes/template.ghtmx`, Line: 40, Col: 26}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(` ` + ghtmx_7f3b9d1a_Var12))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 17, "=\"hello world\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var13 string
		ghtmx_7f3b9d1a_Var13, ghtmx_7f3b9d1a_Err = ghtmx.JoinStringErrs("my-string" + "-attr")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `internal/generator/test-element-attributes/template.ghtmx`, Line: 41, Col: 25}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(` ` + ghtmx_7f3b9d1a_Var13))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		if true {
			var ghtmx_7f3b9d1a_Var14 string
			ghtmx_7f3b9d1a_Var14, ghtmx_7f3b9d1a_Err = ghtmx.JoinStringErrs("bool-" + "attr")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `internal/generator/test-element-attributes/template.ghtmx`, Line: 42, Col: 20}
			}
			_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(` ` + ghtmx_7f3b9d1a_Var14))
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
		}
		if false {
			var ghtmx_7f3b9d1a_Var15 string
			ghtmx_7f3b9d1a_Var15, ghtmx_7f3b9d1a_Err = ghtmx.JoinStringErrs("bool-" + "attr-false")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `internal/generator/test-element-attributes/template.ghtmx`, Line: 43, Col: 26}
			}
			_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(` ` + ghtmx_7f3b9d1a_Var15))
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 18, " data-post=\"/api/secret/unlock\" hx-target=\"#secret\" hx-target-*=\"#errors\" hx-indicator=\"#loading-indicator\"><input type=\"button\" value=\"Unlock\"></form>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

var _ = ghtmxruntime.GeneratedTemplate
