// Code generated by ghtmx - DO NOT EDIT.

// Package ghtmxgen is the central generated package: route path
// constants and typed route constructors, regenerated by ghtmx generate
// from the application's own route registrations.
package ghtmxgen

import (
	"github.com/go-monolith/ghtmx"
)

// SignupPath is the path of POST /signup -> github.com/go-monolith/ghtmx/examples/htmx4-status.Signup (examples/htmx4-status/status.go).
const SignupPath = "/signup"

// SignupHomePath is the path of GET /signup -> github.com/go-monolith/ghtmx/examples/htmx4-status.signupHome (examples/htmx4-status/status.go).
const SignupHomePath = "/signup"

// HTMXScript renders the script tag for the configured htmx version
// (4.0.0) with its subresource-integrity hash (FR-091): the served asset
// must be that exact published build or the browser refuses it (FR-052).
func HTMXScript(opts ...ghtmx.ScriptOption) ghtmx.Component {
	return ghtmx.HTMXScriptTag("4.0.0", opts...)
}
