// Code generated by ghtmx - DO NOT EDIT.

package testscriptusage

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/go-monolith/ghtmx"
import ghtmxruntime "github.com/go-monolith/ghtmx/runtime"

func withParameters(a string, b string, c int) ghtmx.ComponentScript {
	return ghtmx.ComponentScript{
		Name: `__ghtmx_withParameters_1056`,
		Function: `function __ghtmx_withParameters_1056(a, b, c){console.log(a, b, c);
}`,
		Call:       ghtmx.SafeScript(`__ghtmx_withParameters_1056`, a, b, c),
		CallInline: ghtmx.SafeScriptInline(`__ghtmx_withParameters_1056`, a, b, c),
	}
}

func withoutParameters() ghtmx.ComponentScript {
	return ghtmx.ComponentScript{
		Name: `__ghtmx_withoutParameters_6bbf`,
		Function: `function __ghtmx_withoutParameters_6bbf(){alert("hello");
}`,
		Call:       ghtmx.SafeScript(`__ghtmx_withoutParameters_6bbf`),
		CallInline: ghtmx.SafeScriptInline(`__ghtmx_withoutParameters_6bbf`),
	}
}

func onClick() ghtmx.ComponentScript {
	return ghtmx.ComponentScript{
		Name: `__ghtmx_onClick_657d`,
		Function: `function __ghtmx_onClick_657d(){alert("clicked");
}`,
		Call:       ghtmx.SafeScript(`__ghtmx_onClick_657d`),
		CallInline: ghtmx.SafeScriptInline(`__ghtmx_onClick_657d`),
	}
}

func Button(text string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Release := ghtmxruntime.AcquireBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmx_7f3b9d1a_Release(&ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var1 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var1 == nil {
			ghtmx_7f3b9d1a_Var1 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmx.RenderScriptItems(ctx, ghtmx_7f3b9d1a_Buffer, withParameters("test", text, 123), withoutParameters())
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 1, "<button onClick=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var2 ghtmx.ComponentScript = withParameters("test", text, 123)
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var2.Call)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 2, "\" onMouseover=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var3 ghtmx.ComponentScript = withoutParameters()
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var3.Call)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 3, "\" type=\"button\">")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var4 string
		ghtmx_7f3b9d1a_Var4, ghtmx_7f3b9d1a_Err = ghtmx.JoinStringErrs(text)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `internal/generator/test-script-usage/template.ghtmx`, Line: 16, Col: 111}
		}
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var4))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 4, "</button>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func withComment() ghtmx.ComponentScript {
	return ghtmx.ComponentScript{
		Name: `__ghtmx_withComment_9cf8`,
		Function: `function __ghtmx_withComment_9cf8(){//'
}`,
		Call:       ghtmx.SafeScript(`__ghtmx_withComment_9cf8`),
		CallInline: ghtmx.SafeScriptInline(`__ghtmx_withComment_9cf8`),
	}
}

func whenButtonIsClicked(event ghtmx.JSExpression) ghtmx.ComponentScript {
	return ghtmx.ComponentScript{
		Name: `__ghtmx_whenButtonIsClicked_253e`,
		Function: `function __ghtmx_whenButtonIsClicked_253e(event){console.log(event.target)
}`,
		Call:       ghtmx.SafeScript(`__ghtmx_whenButtonIsClicked_253e`, event),
		CallInline: ghtmx.SafeScriptInline(`__ghtmx_whenButtonIsClicked_253e`, event),
	}
}

func ThreeButtons() ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Release := ghtmxruntime.AcquireBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmx_7f3b9d1a_Release(&ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var5 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var5 == nil {
			ghtmx_7f3b9d1a_Var5 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = Button("A").Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = Button("B").Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 5, "<button onMouseover=\"console.log('mouseover')\" type=\"button\">Button C</button> <button hx-on::click=\"alert('clicked inline')\" type=\"button\">Button D</button> ")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmx.RenderScriptItems(ctx, ghtmx_7f3b9d1a_Buffer, onClick())
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 6, "<button hx-on::click=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var6 ghtmx.ComponentScript = onClick()
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var6.Call)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 7, "\" type=\"button\">Button E</button> ")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmx.RenderScriptItems(ctx, ghtmx_7f3b9d1a_Buffer, whenButtonIsClicked(ghtmx.JSExpression("event")))
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 8, "<button onclick=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var7 ghtmx.ComponentScript = whenButtonIsClicked(ghtmx.JSExpression("event"))
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var7.Call)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 9, "\">Button F</button>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = Conditional(true).Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ScriptOnLoad().Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func conditionalScript() ghtmx.ComponentScript {
	return ghtmx.ComponentScript{
		Name: `__ghtmx_conditionalScript_de41`,
		Function: `function __ghtmx_conditionalScript_de41(){alert("conditional");
}`,
		Call:       ghtmx.SafeScript(`__ghtmx_conditionalScript_de41`),
		CallInline: ghtmx.SafeScriptInline(`__ghtmx_conditionalScript_de41`),
	}
}

func Conditional(show bool) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Release := ghtmxruntime.AcquireBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmx_7f3b9d1a_Release(&ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var8 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var8 == nil {
			ghtmx_7f3b9d1a_Var8 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmx.RenderScriptItems(ctx, ghtmx_7f3b9d1a_Buffer, conditionalScript())
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 10, "<input type=\"button\" value=\"Click me\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		if show {
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 11, " onclick=\"")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			var ghtmx_7f3b9d1a_Var9 ghtmx.ComponentScript = conditionalScript()
			_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var9.Call)
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 12, "\"")
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 13, ">")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func alertTest() ghtmx.ComponentScript {
	return ghtmx.ComponentScript{
		Name: `__ghtmx_alertTest_eadf`,
		Function: `function __ghtmx_alertTest_eadf(){alert('testing');
}`,
		Call:       ghtmx.SafeScript(`__ghtmx_alertTest_eadf`),
		CallInline: ghtmx.SafeScriptInline(`__ghtmx_alertTest_eadf`),
	}
}

func ScriptOnLoad() ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Release := ghtmxruntime.AcquireBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmx_7f3b9d1a_Release(&ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var10 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var10 == nil {
			ghtmx_7f3b9d1a_Var10 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmx.RenderScriptItems(ctx, ghtmx_7f3b9d1a_Buffer, alertTest())
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 14, "<script async crossorigin=\"true\" onload=\"")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		var ghtmx_7f3b9d1a_Var11 ghtmx.ComponentScript = alertTest()
		_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx_7f3b9d1a_Var11.Call)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 15, "\" src=\"url.to.some.script\"></script>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

var _ = ghtmxruntime.GeneratedTemplate
