package generatecmd

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// `ghtmx generate` is the command everything else exists to serve, and
// most of its body — route discovery, the central package, the build
// cache, the file walk — only runs on a real project. Driving Run over a
// temp module in-process reaches all of it at once, and unlike the
// watch-mode tests it is deterministic: no watcher, no ports, no timing.

const runTemplate = `package app

templ Page(title string) {
	<html>
		<head><title>{ title }</title></head>
		<body>
			<h1>{ title }</h1>
		</body>
	</html>
}
`

// newProject scaffolds a module holding one template.
func newProject(t *testing.T) string {
	t.Helper()
	// Keep the build cache inside the sandbox rather than writing into
	// the developer's real ~/.cache/ghtmx.
	t.Setenv("GHTMX_CACHE_DIR", t.TempDir())
	dir := t.TempDir()
	files := map[string]string{
		"go.mod":     "module example.com/app\n\ngo 1.25\n",
		"page.ghtmx": runTemplate,
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func runGenerate(t *testing.T, args ...string) (stdout, stderr string, err error) {
	t.Helper()
	var out, errOut bytes.Buffer
	err = Run(context.Background(), &out, &errOut, args)
	return out.String(), errOut.String(), err
}

func TestRunGeneratesAProject(t *testing.T) {
	dir := newProject(t)

	if _, stderr, err := runGenerate(t, "-path", dir, "-include-version=false"); err != nil {
		t.Fatalf("Run: %v\nstderr: %s", err, stderr)
	}

	generated := filepath.Join(dir, "page_ghtmx.go")
	content, err := os.ReadFile(generated)
	if err != nil {
		t.Fatalf("the generated file was not written: %v", err)
	}
	for _, want := range []string{"package app", "func Page(", "Code generated by ghtmx"} {
		if !strings.Contains(string(content), want) {
			t.Errorf("generated output is missing %q", want)
		}
	}
	// -include-version=false must leave the version out, or every
	// toolchain bump churns every generated file in the repository.
	if strings.Contains(string(content), "ghtmx version:") {
		t.Error("the version was embedded despite -include-version=false")
	}
}

// TestRunCheckModeReportsStaleOutput is what CI runs: -check must fail
// when a generated file is out of date, and pass when it is not.
func TestRunCheckModeReportsStaleOutput(t *testing.T) {
	dir := newProject(t)

	// Nothing generated yet, so the check has to fail.
	if _, _, err := runGenerate(t, "-path", dir, "-include-version=false", "-check"); err == nil {
		t.Error("-check passed with no generated file present")
	}

	// Generate, then the same check passes.
	if _, stderr, err := runGenerate(t, "-path", dir, "-include-version=false"); err != nil {
		t.Fatalf("Run: %v\nstderr: %s", err, stderr)
	}
	if _, stderr, err := runGenerate(t, "-path", dir, "-include-version=false", "-check"); err != nil {
		t.Errorf("-check failed on freshly generated output: %v\nstderr: %s", err, stderr)
	}

	// Editing the template makes it stale again. Without this the check
	// would pass on any project that had ever been generated.
	edited := strings.Replace(runTemplate, "<h1>", "<h2>", 1)
	if err := os.WriteFile(filepath.Join(dir, "page.ghtmx"), []byte(edited), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, _, err := runGenerate(t, "-path", dir, "-include-version=false", "-check"); err == nil {
		t.Error("-check passed after the template was edited")
	}
}

// TestRunSingleFileToStdout covers the -f/-stdout pair, which is how
// editors and scripts generate without touching the filesystem.
func TestRunSingleFileToStdout(t *testing.T) {
	dir := newProject(t)
	templ := filepath.Join(dir, "page.ghtmx")

	stdout, stderr, err := runGenerate(t, "-f", templ, "-stdout", "-include-version=false")
	if err != nil {
		t.Fatalf("Run: %v\nstderr: %s", err, stderr)
	}
	if !strings.Contains(stdout, "func Page(") {
		t.Errorf("stdout does not carry the generated code:\n%s", stdout)
	}
	// -stdout must not also write the file.
	if _, err := os.Stat(filepath.Join(dir, "page_ghtmx.go")); err == nil {
		t.Error("-stdout wrote the generated file as well as printing it")
	}
}

// TestRunRegeneratesFromTheBuildCache exercises the cache path: a second
// run over unchanged input must still produce the same file. A cache
// that serves the wrong entry is how a user gets output from a template
// they edited an hour ago.
func TestRunRegeneratesFromTheBuildCache(t *testing.T) {
	dir := newProject(t)

	if _, stderr, err := runGenerate(t, "-path", dir, "-include-version=false"); err != nil {
		t.Fatalf("first run: %v\nstderr: %s", err, stderr)
	}
	first, err := os.ReadFile(filepath.Join(dir, "page_ghtmx.go"))
	if err != nil {
		t.Fatal(err)
	}

	if _, stderr, err := runGenerate(t, "-path", dir, "-include-version=false"); err != nil {
		t.Fatalf("second run: %v\nstderr: %s", err, stderr)
	}
	second, err := os.ReadFile(filepath.Join(dir, "page_ghtmx.go"))
	if err != nil {
		t.Fatal(err)
	}

	if !bytes.Equal(first, second) {
		t.Error("two runs over unchanged input produced different output")
	}
}

// TestRunWithTheCacheDisabled pins that -cache=false still works, which
// is what ensure-generated relies on to test real generation rather than
// a cache hit.
func TestRunWithTheCacheDisabled(t *testing.T) {
	dir := newProject(t)

	if _, stderr, err := runGenerate(t, "-path", dir, "-include-version=false", "-cache=false"); err != nil {
		t.Fatalf("Run: %v\nstderr: %s", err, stderr)
	}
	if _, err := os.Stat(filepath.Join(dir, "page_ghtmx.go")); err != nil {
		t.Errorf("no output with the cache disabled: %v", err)
	}
}

// TestRunReportsAnUnparseableTemplate pins that a broken template fails
// the command rather than leaving stale output in place and exiting 0.
func TestRunReportsAnUnparseableTemplate(t *testing.T) {
	dir := newProject(t)
	if err := os.WriteFile(filepath.Join(dir, "page.ghtmx"),
		[]byte("package app\n\ntempl X() {\n\t<div>\n}\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if _, _, err := runGenerate(t, "-path", dir, "-include-version=false"); err == nil {
		t.Error("Run succeeded on an unparseable template")
	}
}

// TestRunOnAMissingPath pins the early failure: a typo'd -path must say
// so rather than silently generating nothing and reporting success.
func TestRunOnAMissingPath(t *testing.T) {
	missing := filepath.Join(t.TempDir(), "no-such-dir")

	if _, _, err := runGenerate(t, "-path", missing); err == nil {
		t.Error("Run succeeded on a path that does not exist")
	}
}

// TestRunWithSourceMapVisualisations covers the -source-map-visualisations
// path, which bypasses the cache and writes the side-by-side HTML the
// visualize package renders.
func TestRunWithSourceMapVisualisations(t *testing.T) {
	dir := newProject(t)

	if _, stderr, err := runGenerate(t, "-path", dir, "-include-version=false",
		"-source-map-visualisations"); err != nil {
		t.Fatalf("Run: %v\nstderr: %s", err, stderr)
	}

	var found bool
	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(path, ".html") {
			found = true
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if !found {
		t.Error("no visualisation HTML was written")
	}
}
