// Code generated by ghtmx - DO NOT EDIT.

package site

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/go-monolith/ghtmx"
import ghtmxruntime "github.com/go-monolith/ghtmx/runtime"

import "github.com/go-monolith/ghtmx/docs/official/ghtmxgen"

// homeBody is the landing content: the site-only index.md plus a hero
// whose links are bound to real routes.
// ghtmxFragmentBody_homeBody is the shared body of fragment homeBody: both entry
// points and every declaration site execute it, so the render modes cannot
// diverge.
func ghtmxFragmentBody_homeBody(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput, intro string) (ghtmx_7f3b9d1a_Err error) {
	ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
	if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
		return ghtmx_7f3b9d1a_CtxErr
	}
	ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
	if !ghtmx_7f3b9d1a_IsBuffer {
		defer func() {
			ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
			if ghtmx_7f3b9d1a_Err == nil {
				ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
			}
		}()
	}
	ctx = ghtmx.InitializeContext(ctx)
	ctx = ghtmx.ClearChildren(ctx)
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 1, "<article id=\"home\">")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmx.Raw(intro).Render(ctx, ghtmx_7f3b9d1a_Buffer)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 2, "<p class=\"hero\"><a href=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var1 ghtmx.SafeURL
	ghtmx_7f3b9d1a_Var1, ghtmx_7f3b9d1a_Err = ghtmx.JoinURLErrs(ghtmx.URL(ghtmxgen.GettingStartedPath))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `site/home.ghtmx`, Line: 11, Col: 51}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var1))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 3, "\" hx-get=\"/getting-started\" hx-target=\"#content\" hx-swap=\"innerHTML\" hx-push-url=\"true\">Get started</a> <a href=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var2 ghtmx.SafeURL
	ghtmx_7f3b9d1a_Var2, ghtmx_7f3b9d1a_Err = ghtmx.JoinURLErrs(ghtmx.URL(ghtmxgen.ExamplesIndexPath))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `site/home.ghtmx`, Line: 12, Col: 50}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var2))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 4, "\" hx-get=\"/examples\" hx-target=\"#content\" hx-swap=\"innerHTML\" hx-push-url=\"true\">Browse the examples</a></p></article>")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	return nil
}

// homeBody renders the fragment inline as a component.
func homeBody(intro string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) error {
		return ghtmxFragmentBody_homeBody(ghtmx_7f3b9d1a_Input, intro)
	})
}

// homeBodyFragment renders only the fragment, for an htmx swap (FR-031).
func homeBodyFragment(intro string) ghtmx.Fragment {
	return ghtmxruntime.GeneratedFragment(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) error {
		return ghtmxFragmentBody_homeBody(ghtmx_7f3b9d1a_Input, intro)
	})
}

func homePage(intro string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		if !ghtmx_7f3b9d1a_IsBuffer {
			defer func() {
				ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
				if ghtmx_7f3b9d1a_Err == nil {
					ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
				}
			}()
		}
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var3 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var3 == nil {
			ghtmx_7f3b9d1a_Var3 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Var4 := ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
			ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
			ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
			if !ghtmx_7f3b9d1a_IsBuffer {
				defer func() {
					ghtmx_7f3b9d1a_BufErr := ghtmxruntime.ReleaseBuffer(ghtmx_7f3b9d1a_Buffer)
					if ghtmx_7f3b9d1a_Err == nil {
						ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_BufErr
					}
				}()
			}
			ctx = ghtmx.InitializeContext(ctx)
			ghtmx_7f3b9d1a_Err = homeBody(intro).Render(ctx, ghtmx_7f3b9d1a_Buffer)
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			return nil
		})
		ghtmx_7f3b9d1a_Err = shell("home").Render(ghtmx.WithChildren(ctx, ghtmx_7f3b9d1a_Var4), ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

// Handlers bound from hx-* attributes: the references keep imports
// used and the symbols compile-checked.
var (
	_ = ExamplesIndex
	_ = GettingStarted
)

var _ = ghtmxruntime.GeneratedTemplate
