// Code generated by ghtmx - DO NOT EDIT.

package site

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/go-monolith/ghtmx"
import ghtmxruntime "github.com/go-monolith/ghtmx/runtime"

import "github.com/go-monolith/ghtmx/docs/official/ghtmxgen"

// homeBody is the landing content: a hero, the three language
// pillars, a code sample, and the site-only index.md rendered below.
// ghtmxFragmentBody_homeBody is the shared body of fragment homeBody: both entry
// points and every declaration site execute it, so the render modes cannot
// diverge.
func ghtmxFragmentBody_homeBody(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput, intro string) (ghtmx_7f3b9d1a_Err error) {
	ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
	if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
		return ghtmx_7f3b9d1a_CtxErr
	}
	ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
	defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
	ctx = ghtmx.InitializeContext(ctx)
	ctx = ghtmx.ClearChildren(ctx)
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 1, "<article id=\"home\" class=\"home\"><div class=\"hero\"><h1 class=\"hero-title\">ghtmx <span class=\"hero-accent\">— build HTML with Go and htmx</span></h1><p class=\"hero-tagline\">A templ-compatible template engine that makes htmx a compile-checked language concept: every URL, fragment, and server event in your templates is verified against your Go code at build time.</p><p class=\"hero-actions\"><a class=\"btn btn-primary\" href=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var1 ghtmx.SafeURL
	ghtmx_7f3b9d1a_Var1, ghtmx_7f3b9d1a_Err = ghtmx.JoinURLErrs(ghtmx.URL(ghtmxgen.GettingStartedPath))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `site/home.ghtmx`, Line: 13, Col: 76}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var1))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 2, "\" hx-get=\"/getting-started\">Get started</a> <a class=\"btn\" href=\"")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var2 ghtmx.SafeURL
	ghtmx_7f3b9d1a_Var2, ghtmx_7f3b9d1a_Err = ghtmx.JoinURLErrs(ghtmx.URL(ghtmxgen.ExamplesIndexPath))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `site/home.ghtmx`, Line: 14, Col: 63}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var2))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 3, "\" hx-get=\"/examples\">Browse examples</a> <a class=\"btn\" href=\"https://github.com/go-monolith/ghtmx\" target=\"_blank\" rel=\"noopener\">GitHub</a></p></div><div class=\"features\"><div class=\"feature\"><h3>Route-aware bindings</h3><p>Every hx-get and hx-post URL resolves against a real Go route at build time — rename a route and the build breaks at every binding site.</p></div><div class=\"feature\"><h3>Compile-time fragments</h3><p><code>fragment</code> blocks render inline in a page and standalone for htmx swaps, byte-identically — no drift between full pages and partial updates.</p></div><div class=\"feature\"><h3>Typed server events</h3><p><code>event</code> declarations generate the only HX-Trigger emitters, with typed payloads shared by handlers and templates.</p></div></div><pre class=\"hero-code\"><code class=\"language-templ\">")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	var ghtmx_7f3b9d1a_Var3 string
	ghtmx_7f3b9d1a_Var3, ghtmx_7f3b9d1a_Err = ghtmx.JoinStringErrs(heroCode)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx.Error{Err: ghtmx_7f3b9d1a_Err, FileName: `site/home.ghtmx`, Line: 32, Col: 64}
	}
	_, ghtmx_7f3b9d1a_Err = ghtmx_7f3b9d1a_Buffer.WriteString(ghtmx.EscapeString(ghtmx_7f3b9d1a_Var3))
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 4, "</code></pre>")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmx.Raw(intro).Render(ctx, ghtmx_7f3b9d1a_Buffer)
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 5, "</article>")
	if ghtmx_7f3b9d1a_Err != nil {
		return ghtmx_7f3b9d1a_Err
	}
	return nil
}

// homeBody renders the fragment inline as a component.
func homeBody(intro string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) error {
		return ghtmxFragmentBody_homeBody(ghtmx_7f3b9d1a_Input, intro)
	})
}

// homeBodyFragment renders only the fragment, for an htmx swap (FR-031).
func homeBodyFragment(intro string) ghtmx.Fragment {
	return ghtmxruntime.GeneratedFragment(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) error {
		return ghtmxFragmentBody_homeBody(ghtmx_7f3b9d1a_Input, intro)
	})
}

func homePage(intro string) ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var4 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var4 == nil {
			ghtmx_7f3b9d1a_Var4 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Var5 := ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
			ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
			ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer := ghtmxruntime.GetBuffer(ghtmx_7f3b9d1a_W)
			defer ghtmxruntime.ReleaseAcquiredBuffer(ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_IsBuffer, &ghtmx_7f3b9d1a_Err)
			ctx = ghtmx.InitializeContext(ctx)
			ghtmx_7f3b9d1a_Err = homeBody(intro).Render(ctx, ghtmx_7f3b9d1a_Buffer)
			if ghtmx_7f3b9d1a_Err != nil {
				return ghtmx_7f3b9d1a_Err
			}
			return nil
		})
		ghtmx_7f3b9d1a_Err = shell("home").Render(ghtmx.WithChildren(ctx, ghtmx_7f3b9d1a_Var5), ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

// Handlers bound from hx-* attributes: the references keep imports
// used and the symbols compile-checked.
var (
	_ = ExamplesIndex
	_ = GettingStarted
)

var _ = ghtmxruntime.GeneratedTemplate
