// Code generated by ghtmx - DO NOT EDIT.

package testtextinlineexpression

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/go-monolith/ghtmx"
import ghtmxruntime "github.com/go-monolith/ghtmx/runtime"

func icon() ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Release := ghtmxruntime.AcquireBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmx_7f3b9d1a_Release(&ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var1 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var1 == nil {
			ghtmx_7f3b9d1a_Var1 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 1, "<svg></svg>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

func InlineComponentAfterText() ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Release := ghtmxruntime.AcquireBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmx_7f3b9d1a_Release(&ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var2 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var2 == nil {
			ghtmx_7f3b9d1a_Var2 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 2, "<div>Label: ")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = icon().Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 3, "</div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

const InlineComponentAfterTextExpected = `<div>Label: <svg></svg></div>`

func EmailAddress() ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Release := ghtmxruntime.AcquireBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmx_7f3b9d1a_Release(&ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var3 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var3 == nil {
			ghtmx_7f3b9d1a_Var3 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 4, "<span>user@example.com</span>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

const EmailAddressExpected = `<span>user@example.com</span>`

func InlineComponentBetweenText() ghtmx.Component {
	return ghtmxruntime.GeneratedTemplate(func(ghtmx_7f3b9d1a_Input ghtmxruntime.GeneratedComponentInput) (ghtmx_7f3b9d1a_Err error) {
		ghtmx_7f3b9d1a_W, ctx := ghtmx_7f3b9d1a_Input.Writer, ghtmx_7f3b9d1a_Input.Context
		if ghtmx_7f3b9d1a_CtxErr := ctx.Err(); ghtmx_7f3b9d1a_CtxErr != nil {
			return ghtmx_7f3b9d1a_CtxErr
		}
		ghtmx_7f3b9d1a_Buffer, ghtmx_7f3b9d1a_Release := ghtmxruntime.AcquireBuffer(ghtmx_7f3b9d1a_W)
		defer ghtmx_7f3b9d1a_Release(&ghtmx_7f3b9d1a_Err)
		ctx = ghtmx.InitializeContext(ctx)
		ghtmx_7f3b9d1a_Var4 := ghtmx.GetChildren(ctx)
		if ghtmx_7f3b9d1a_Var4 == nil {
			ghtmx_7f3b9d1a_Var4 = ghtmx.NopComponent
		}
		ctx = ghtmx.ClearChildren(ctx)
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 5, "<div>Before ")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = icon().Render(ctx, ghtmx_7f3b9d1a_Buffer)
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		ghtmx_7f3b9d1a_Err = ghtmxruntime.WriteString(ghtmx_7f3b9d1a_Buffer, 6, " after</div>")
		if ghtmx_7f3b9d1a_Err != nil {
			return ghtmx_7f3b9d1a_Err
		}
		return nil
	})
}

const InlineComponentBetweenTextExpected = `<div>Before <svg></svg> after</div>`

var _ = ghtmxruntime.GeneratedTemplate
